/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.ventanaProducto;

import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.modelo.Producto;
import java.util.Collection;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dduta
 */
public class ListarProductos extends javax.swing.JInternalFrame {

    private ControladorProducto controladorProducto;
    private Locale localizacion;
    private ResourceBundle mensajes;
    private String codigo;
    private String descripcion;
    private String precio;

    /**
     * Creates new form ListarProductos
     */
    public ListarProductos(ControladorProducto controladorProducto) {
        initComponents();
        this.mensajes = mensajes;
        cambiarIdioma(mensajes);
        this.controladorProducto = controladorProducto;
    }

    public void cambiarIdioma(ResourceBundle mensajes) {
        mensajes = ResourceBundle.getBundle("ec.edu.ups.Idiomas.mensajes", Locale.getDefault());
        ButtonListarP.setText(mensajes.getString("ButtonListarP"));
        ButtoCancelarListarP.setText(mensajes.getString("ButtoCancelarListarP"));
        
        this.codigo=mensajes.getString("codigop");
        this.descripcion=mensajes.getString("descripcionp");
        this.precio=mensajes.getString("preciop");
        
        DefaultTableModel modelo = (DefaultTableModel) tablaListarP.getModel();
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
        modelo.addColumn(codigo);
        modelo.addColumn(descripcion);
        modelo.addColumn(precio);
        this.tablaListarP.setModel(modelo);
    }
     public void limpiarTblLista() {
       tablaListarP.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListarP = new javax.swing.JTable();
        ButtonListarP = new javax.swing.JButton();
        ButtoCancelarListarP = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Listar Productos");

        tablaListarP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaListarP);

        ButtonListarP.setText("Listar");
        ButtonListarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarPActionPerformed(evt);
            }
        });

        ButtoCancelarListarP.setText("Cancelar");
        ButtoCancelarListarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtoCancelarListarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(ButtonListarP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(ButtoCancelarListarP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonListarP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtoCancelarListarP))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonListarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarPActionPerformed
        Collection<Producto> listaProductos = controladorProducto.findAll();
        DefaultTableModel modelo = (DefaultTableModel) tablaListarP.getModel();
        modelo.setRowCount(0);
        for (Producto producto : listaProductos) {
            Object[] rowData = {producto.getCodigo(), producto.getDescripcion(), producto.getPrecio()};
            modelo.addRow(rowData);  
        }
    }//GEN-LAST:event_ButtonListarPActionPerformed

    private void ButtoCancelarListarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtoCancelarListarPActionPerformed

       
        this.setVisible(false);
        
    }//GEN-LAST:event_ButtoCancelarListarPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtoCancelarListarP;
    private javax.swing.JButton ButtonListarP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaListarP;
    // End of variables declaration//GEN-END:variables
}
