/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.ventanaCarrito;

import ec.edu.ups.controlador.*;
import ec.edu.ups.modelo.Producto;
import java.util.Collection;
import java.util.HashSet;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dduta
 */
public class CrearCarrito extends javax.swing.JInternalFrame {

    private ControladorCarrito controladorCarrito;
    private ControladorProducto controladorProducto;
    private ControladorUsuario controladorUsuario;
    private Locale localizacion;
    private ResourceBundle mensajes;
    private String codigo;
    private String descripcion;
    private String precio;

    /**
     * Creates new form CrearCarrito
     */
    public CrearCarrito(ControladorCarrito controladorCarrito, ControladorProducto controladorProducto, ControladorUsuario controladorUsuario) {
        initComponents();
        this.mensajes = mensajes;
        cambiarIdioma(mensajes);
        this.controladorCarrito = controladorCarrito;
        this.controladorProducto = controladorProducto;
        this.controladorUsuario = controladorUsuario;

    }

    public CrearCarrito(ControladorProducto controladorProducto) {
        this.controladorProducto = controladorProducto;
    }

    public void limpiar() {
        txtNumeroC.setText("");
    }

    public void limpiarTblLista() {
       tablaMostrarP.removeAll();
    }

    public void cambiarIdioma(ResourceBundle mensajes) {
        mensajes = ResourceBundle.getBundle("ec.edu.ups.Idiomas.mensajes", Locale.getDefault());
        nn.setText(mensajes.getString("nn"));
        bootonActualizar.setText(mensajes.getString("bootonActualizar"));
        btnAgragarListaP.setText(mensajes.getString("btnAgragarListaP"));
        ButtonCrearC.setText(mensajes.getString("ButtonCrearC"));
        ButtonCancelarCrearP.setText(mensajes.getString("ButtonCancelarCrearP"));
        
        this.codigo=mensajes.getString("codigop");
        this.descripcion=mensajes.getString("descripcionp");
        this.precio=mensajes.getString("preciop");
        
        DefaultTableModel modelo = (DefaultTableModel) tablaMostrarP.getModel();
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
        modelo.addColumn(codigo);
        modelo.addColumn(descripcion);
        modelo.addColumn(precio);
        this.tablaMostrarP.setModel(modelo);
        
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn(codigo);
        model.addColumn(descripcion);
        model.addColumn(precio);
        this.tblProductos.setModel(model);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nn = new javax.swing.JLabel();
        txtNumeroC = new javax.swing.JTextField();
        ButtonCrearC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMostrarP = new javax.swing.JTable();
        bootonActualizar = new javax.swing.JButton();
        btnAgragarListaP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        ButtonCancelarCrearP = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Creacion de carritos de Compras");

        nn.setText("Ingrese el numero del Carrto:");

        txtNumeroC.setToolTipText("Ingresa el numero del carrito");
        txtNumeroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCActionPerformed(evt);
            }
        });

        ButtonCrearC.setText("Crear");
        ButtonCrearC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCrearCActionPerformed(evt);
            }
        });

        tablaMostrarP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMostrarP);

        bootonActualizar.setText("Actualizar");
        bootonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bootonActualizarActionPerformed(evt);
            }
        });

        btnAgragarListaP.setText("Agregar a la lista");
        btnAgragarListaP.setToolTipText("Dale push por cada producto que selleciones para agregar ala lista del carrito");
        btnAgragarListaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgragarListaPActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        ButtonCancelarCrearP.setText("Cancelar");
        ButtonCancelarCrearP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarCrearPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nn)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bootonActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgragarListaP)
                .addGap(239, 239, 239))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(ButtonCrearC, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(ButtonCancelarCrearP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nn)
                    .addComponent(txtNumeroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(bootonActualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnAgragarListaP)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCrearC)
                    .addComponent(ButtonCancelarCrearP))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCActionPerformed

    private void ButtonCrearCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCrearCActionPerformed

        if (!txtNumeroC.getText().isEmpty()) {
            if (controladorCarrito.read(Integer.valueOf(txtNumeroC.getText())) == null) {
                Set<Integer> productos = new HashSet<>();
                int filas = tblProductos.getRowCount();
                for (int i = 0; i < filas; i++) {
                    int codigo = Integer.parseInt(tblProductos.getValueAt(i, 0).toString());
                    productos.add(codigo);
                }

                controladorCarrito.create(Integer.valueOf(txtNumeroC.getText()), controladorUsuario.verUsuario(), productos);
                JOptionPane.showMessageDialog(null, "carrito creado");
                limpiar();
               limpiarTblLista();
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "codigo ya existente");
                limpiar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingresa un codigo");
        }
    }//GEN-LAST:event_ButtonCrearCActionPerformed

    private void bootonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bootonActualizarActionPerformed
        Collection<Producto> listap = controladorProducto.findAll();
        
        DefaultTableModel modelo = (DefaultTableModel)tablaMostrarP.getModel();
        modelo.setRowCount(0);
        tablaMostrarP.setModel(modelo);
        for (Producto producto : listap) {
            Object[] rowData = {producto.getCodigo(), producto.getDescripcion(), producto.getPrecio()};
            modelo.addRow(rowData);
        }
        tablaMostrarP.setModel(modelo);
    }//GEN-LAST:event_bootonActualizarActionPerformed

    private void btnAgragarListaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgragarListaPActionPerformed
        int fila = tablaMostrarP.getSelectedRow();

        int codigo = Integer.parseInt(tablaMostrarP.getValueAt(fila, 0).toString());
        String descripcion = tablaMostrarP.getValueAt(fila, 1).toString();
        double total = Double.parseDouble(tablaMostrarP.getValueAt(fila, 2).toString());

        DefaultTableModel model = (DefaultTableModel)tblProductos.getModel();
        tblProductos.setModel(model);
        Object[] rowData = {codigo, descripcion, total};
        model.addRow(rowData);
        tblProductos.setModel(model);

    }//GEN-LAST:event_btnAgragarListaPActionPerformed

    private void ButtonCancelarCrearPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarCrearPActionPerformed
        limpiar();
        this.setVisible(false);
    }//GEN-LAST:event_ButtonCancelarCrearPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelarCrearP;
    private javax.swing.JButton ButtonCrearC;
    private javax.swing.JButton bootonActualizar;
    private javax.swing.JButton btnAgragarListaP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nn;
    private javax.swing.JTable tablaMostrarP;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtNumeroC;
    // End of variables declaration//GEN-END:variables
}
