/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.ventanaCarrito;

import ec.edu.ups.controlador.ControladorCarrito;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author dduta
 */
public class EliminarCarrito extends javax.swing.JInternalFrame {

    private ControladorCarrito controladorCarrito;
    private Locale localizacion;
    private ResourceBundle mensajes;

    /**
     * Creates new form EliminarCarrito
     */
    public EliminarCarrito(ControladorCarrito controladorCarrito) {
        initComponents();
        this.mensajes = mensajes;
        cambiarIdioma(mensajes);
        this.controladorCarrito = controladorCarrito;
    }

    public void limpiar() {
        txtEliminarC.setText("");
    }

    public void cambiarIdioma(ResourceBundle mensajes) {
        mensajes = ResourceBundle.getBundle("ec.edu.ups.Idiomas.mensajes", Locale.getDefault());
        carritoeliminarnumero.setText(mensajes.getString("carritoeliminarnumero"));
        ButtonEliminarC.setText(mensajes.getString("ButtonEliminarC"));
        ButtonCancelarEliminarC.setText(mensajes.getString("ButtonCancelarEliminarC"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carritoeliminarnumero = new javax.swing.JLabel();
        ButtonEliminarC = new javax.swing.JButton();
        txtEliminarC = new javax.swing.JTextField();
        ButtonCancelarEliminarC = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Eliminacion de Carritos");

        carritoeliminarnumero.setText("Ingrese el numero del  Carrito a Eliminar:");

        ButtonEliminarC.setText("Eliminar");
        ButtonEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarCActionPerformed(evt);
            }
        });

        txtEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEliminarCActionPerformed(evt);
            }
        });

        ButtonCancelarEliminarC.setText("Cancelar");
        ButtonCancelarEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelarEliminarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(carritoeliminarnumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEliminarC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(ButtonEliminarC)
                        .addGap(37, 37, 37)
                        .addComponent(ButtonCancelarEliminarC)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carritoeliminarnumero)
                    .addComponent(txtEliminarC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonEliminarC)
                    .addComponent(ButtonCancelarEliminarC))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEliminarCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEliminarCActionPerformed

    private void ButtonEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarCActionPerformed
        if (!txtEliminarC.getText().isEmpty()) {
            if (controladorCarrito.read(Integer.valueOf(txtEliminarC.getText())) != null) {
                controladorCarrito.delete(Integer.valueOf(txtEliminarC.getText()));
                JOptionPane.showMessageDialog(null, "Carrito Eliminado");
                limpiar();
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "El carrito no Existe");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llena todos los Campos");
        }
    }//GEN-LAST:event_ButtonEliminarCActionPerformed

    private void ButtonCancelarEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelarEliminarCActionPerformed
        limpiar();
        this.setVisible(false);
    }//GEN-LAST:event_ButtonCancelarEliminarCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancelarEliminarC;
    private javax.swing.JButton ButtonEliminarC;
    private javax.swing.JLabel carritoeliminarnumero;
    private javax.swing.JTextField txtEliminarC;
    // End of variables declaration//GEN-END:variables
}
