/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.ventanaCarrito;

import ec.edu.ups.controlador.ControladorCarrito;
import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.modelo.Carrito;
import ec.edu.ups.modelo.Producto;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dduta
 */
public class ListarCarrito extends javax.swing.JInternalFrame {

    private ControladorCarrito controladorCarrito;
    private ControladorProducto controladorProducto;
    private ControladorUsuario controladorUsuario;
    private Locale localizacion;
    private ResourceBundle mensajes;

    /**
     * Creates new form ListarCarrito
     */
    public ListarCarrito(ControladorCarrito controladorCarrito,ControladorUsuario controladorUsuario, ControladorProducto controladorProducto) {
        initComponents();
        this.mensajes = mensajes;
        cambiarIdioma(mensajes);
        this.controladorCarrito = controladorCarrito;
        this.controladorUsuario=controladorUsuario;
        this.controladorProducto=controladorProducto;
    }

    public String getTitle() {
        return title;
    }

    public void cambiarIdioma(ResourceBundle mensajes) {
        mensajes = ResourceBundle.getBundle("ec.edu.ups.Idiomas.mensajes", Locale.getDefault());
        ButtonListarCrrito.setText(mensajes.getString("ButtonListarCrrito"));
        ListarCarritoCedula.setText(mensajes.getString("ListarCarritoCedula"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        ButtonListarCrrito = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtCdeulaListarC = new javax.swing.JTextField();
        ListarCarritoCedula = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Lista de todos los Carritos Creados");

        ButtonListarCrrito.setText("Listar");
        ButtonListarCrrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListarCrritoActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        ListarCarritoCedula.setText("Ingrese numero de cedula o correo para listar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ListarCarritoCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCdeulaListarC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(ButtonListarCrrito, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ListarCarritoCedula)
                        .addComponent(txtCdeulaListarC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonListarCrrito, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonListarCrritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListarCrritoActionPerformed
     if (!txtCdeulaListarC.getText().isEmpty()) {
         if(controladorUsuario.read(txtCdeulaListarC.getText())!=null){
             String cedula=txtCdeulaListarC.getText();
             String cliente=controladorUsuario.read(cedula).getId();
          jTextArea1.setText(controladorCarrito.ListarCarritoPorCdedulaOCorreo("cedula", cliente).toString()); 
         }else{
            JOptionPane.showMessageDialog(null, "El Usuario no existe");  
         }
        } else {
            JOptionPane.showMessageDialog(null, "Ingresa una Cedula para listar");
        }
    }//GEN-LAST:event_ButtonListarCrritoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonListarCrrito;
    private javax.swing.JLabel ListarCarritoCedula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtCdeulaListarC;
    // End of variables declaration//GEN-END:variables
}
